package com.example.ssmspringboot2.util;

public class Constant {
    public static int port = 8080;
    public static String pokemon = "pokemon";
    public static String pokemonType = "type";
    public static String pokemonGeneration = "generation";
    public static String pokemonStat = "stat";
    public static String pokemonAbility = "ability";
    public static String pokemonForm = "pokemon-form";
    public static String pokemonSpecies = "pokemon-species";
    public static String pokemonMove = "move";
    public static String versionGroup = "version-group";
    public static String moveLearnMethod = "move-learn-method";
    public static String pokemonVersion = "version";
    public static String pokemonItem = "item";
    public static String pokemonNature = "nature";
    public static String moveDamageClass = "move-damage-class";
    public static String language = "language";
    public static String characteristic = "characteristic";
    public static String itemCategory = "item-category";
    public static String itemFlingEffect = "item-fling-effect";
    public static String itemAttributes = "item_attribute";
    public static String machine = "machine";
    public static String evolutionChain = "evolution-chain";
    public static String pokemonColor = "pokemon-color";
    public static String pokemonHabitat = "pokemon-habitat";
    public static String pokemonShape = "pokemon-shape";
    public static String growthRate = "growth-rate";
    public static String eggGroup = "egg-group";
    public static String palParkArea = "pal_park_area";
    public static String pokedex = "pokedex";
    public static String contestType = "contest-type";
    public static String contestEffect = "contest-effect";
    public static String target = "move-target";
    public static String superContestEffect = "super-contest-effect";
    public static String moveCategory = "move-category";
    public static String moveAilment = "move-ailment";
    public static String region = "region";
    public static String berryFlavor = "berry-flavor";
    public static String moveBattleStyle = "move-battle-style";
    public static String pokeathlonStat = "pokeathlon-stat";
}
